# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on: 
  schedule:
    - cron: "55 19 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: /Intro
        # Name of output zip file
        dest: intro.zip
        # Whether to add subdirectories to simply zip all files to the root
        recursive: true
